"""Added Cleaner model

Revision ID: dff495464dab
Revises: 77c9cfe256ce
Create Date: 2023-12-12 12:39:50.930991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff495464dab'
down_revision: Union[str, None] = '77c9cfe256ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaners',
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=25), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cleaner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleaners')
    # ### end Alembic commands ###
